package com.farmdirect.app.util

import android.content.Context
import android.content.Intent
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileWriter
import java.text.SimpleDateFormat
import java.util.*

class DataExportService(private val context: Context) {
    
    data class ExportData(
        val sales: List<Map<String, Any>>,
        val expenses: List<Map<String, Any>>,
        val totalRevenue: Double,
        val totalExpenses: Double,
        val netProfit: Double,
        val period: String
    )
    
    fun exportToCSV(data: ExportData): File {
        val dateFormat = SimpleDateFormat("yyyy-MM-dd_HH-mm-ss", Locale.US)
        val fileName = "FarmDirect_Export_${dateFormat.format(Date())}.csv"
        val file = File(context.cacheDir, fileName)
        
        FileWriter(file).use { writer ->
            writer.append("FarmDirect Export - ${data.period}\n\n")
            
            // Sales section
            writer.append("SALES\n")
            writer.append("Date,Item,Quantity,Unit,Unit Price,Total,Status\n")
            data.sales.forEach { sale ->
                writer.append("${sale["date"]},${sale["item"]},${sale["quantity"]},${sale["unit"]},${sale["unitPrice"]},${sale["total"]},${sale["status"]}\n")
            }
            
            writer.append("\nEXPENSES\n")
            writer.append("Date,Category,Description,Amount\n")
            data.expenses.forEach { expense ->
                writer.append("${expense["date"]},${expense["category"]},${expense["description"]},${expense["amount"]}\n")
            }
            
            writer.append("\nSUMMARY\n")
            writer.append("Total Revenue,KES ${"%,.0f".format(data.totalRevenue)}\n")
            writer.append("Total Expenses,KES ${"%,.0f".format(data.totalExpenses)}\n")
            writer.append("Net Profit,KES ${"%,.0f".format(data.netProfit)}\n")
        }
        
        return file
    }
    
    fun exportToPDF(data: ExportData): File {
        val dateFormat = SimpleDateFormat("yyyy-MM-dd_HH-mm-ss", Locale.US)
        val fileName = "FarmDirect_Export_${dateFormat.format(Date())}.txt"
        val file = File(context.cacheDir, fileName)
        
        FileWriter(file).use { writer ->
            writer.append("═══════════════════════════════\n")
            writer.append("    FARMDIRECT EXPORT REPORT    \n")
            writer.append("    ${data.period}               \n")
            writer.append("═══════════════════════════════\n\n")
            
            writer.append("SALES SUMMARY\n")
            writer.append("───────────────────────────────\n")
            data.sales.forEach { sale ->
                writer.append("${sale["date"]} | ${sale["item"]} | ${sale["quantity"]}${sale["unit"]} | KES ${sale["total"]}\n")
            }
            
            writer.append("\nFINANCIAL SUMMARY\n")
            writer.append("───────────────────────────────\n")
            writer.append("Total Revenue:    KES ${"%,.0f".format(data.totalRevenue)}\n")
            writer.append("Total Expenses:   KES ${"%,.0f".format(data.totalExpenses)}\n")
            writer.append("Net Profit:       KES ${"%,.0f".format(data.netProfit)}\n")
            
            writer.append("\n═══════════════════════════════\n")
            writer.append("Generated by FarmDirect App\n")
            writer.append("Date: ${SimpleDateFormat("dd/MM/yyyy HH:mm", Locale.US).format(Date())}\n")
            writer.append("═══════════════════════════════\n")
        }
        
        return file
    }
    
    fun shareFile(file: File) {
        val uri = FileProvider.getUriForFile(context, "${context.packageName}.provider", file)
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "text/*"
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(intent, "Share Report"))
    }
}
