package com.farmdirect.app.util

import android.content.Context

object StringResources {
    
    private val translations = mapOf(
        "en" to mapOf(
            "app_name" to "FarmDirect",
            "tagline" to "Connect Direct • Farm to Table",
            "home" to "Home",
            "search" to "Search",
            "sell" to "Sell",
            "messages" to "Messages",
            "profile" to "Profile",
            "login" to "Sign In",
            "register" to "Create Account",
            "welcome" to "Welcome Back!",
            "good_morning" to "Good Morning!",
            "find_produce" to "Find Fresh Produce Near You",
            "buy_now" to "Buy Now",
            "post_harvest" to "Post Your Harvest",
            "weather" to "Weather",
            "finance" to "Farm Wallet",
            "academy" to "Farming Academy",
            "offline" to "You are offline",
            "online" to "You are online",
            "syncing" to "Syncing...",
            "download_offline" to "Download for Offline",
            "pending_sync" to "items pending sync",
            "sync_now" to "Sync Now",
            "clear_data" to "Clear Offline Data",
            "payment" to "Payment",
            "pay_mpesa" to "Pay with M-Pesa",
            "order" to "Order",
            "delivery" to "Delivery",
            "tracking" to "Track Delivery",
            "chat" to "Chat",
            "call" to "Call",
            "video_call" to "Video Call",
            "voice_call" to "Voice Call",
            "end_call" to "End",
            "mute" to "Mute",
            "speaker" to "Speaker",
            "camera" to "Camera",
            "save" to "Save",
            "cancel" to "Cancel",
            "delete" to "Delete",
            "edit" to "Edit",
            "share" to "Share",
            "rate" to "Rate",
            "review" to "Review",
            "report" to "Report",
            "help" to "Help",
            "settings" to "Settings",
            "logout" to "Sign Out",
            "loading" to "Loading...",
            "error" to "Something went wrong",
            "retry" to "Try Again",
            "no_results" to "No results found",
            "empty_chats" to "No messages yet",
            "empty_orders" to "No orders yet",
            "crops" to "Crops",
            "livestock" to "Livestock",
            "products" to "Products",
            "services" to "Services",
            "price" to "Price",
            "quantity" to "Quantity",
            "quality" to "Quality",
            "location" to "Location",
            "description" to "Description",
            "organic" to "Organic",
            "grade" to "Grade",
            "farmer" to "Farmer",
            "buyer" to "Buyer",
            "rider" to "Rider",
            "verified" to "Verified",
            "rating" to "Rating",
            "sales" to "Sales",
            "orders" to "Orders",
            "earnings" to "Earnings",
            "savings" to "Savings",
            "loan" to "Loan",
            "insure" to "Insure"
        ),
        
        "sw" to mapOf(
            "app_name" to "FarmDirect",
            "tagline" to "Unganisha Moja kwa Moja • Shamba hadi Mezani",
            "home" to "Nyumbani",
            "search" to "Tafuta",
            "sell" to "Uza",
            "messages" to "Ujumbe",
            "profile" to "Wasifu",
            "login" to "Ingia",
            "register" to "Jisajili",
            "welcome" to "Karibu Tena!",
            "good_morning" to "Habari za Asubuhi!",
            "find_produce" to "Pata Mazao Mapya Karibu Nawe",
            "buy_now" to "Nunua Sasa",
            "post_harvest" to "Weka Mavuno Yako",
            "weather" to "Hali ya Hewa",
            "finance" to "Pesa za Shambani",
            "academy" to "Chuo cha Kilimo",
            "offline" to "Huna mtandao",
            "online" to "Uko mtandaoni",
            "syncing" to "Inasawazisha...",
            "download_offline" to "Pakua kwa Matumizi ya Nje ya Mtandao",
            "pending_sync" to "vitu vinasubiri kusawazishwa",
            "sync_now" to "Sawazisha Sasa",
            "clear_data" to "Futa Data ya Nje ya Mtandao",
            "payment" to "Malipo",
            "pay_mpesa" to "Lipa kwa M-Pesa",
            "order" to "Agizo",
            "delivery" to "Usafirishaji",
            "tracking" to "Fuatilia Usafirishaji",
            "chat" to "Ongea",
            "call" to "Piga Simu",
            "video_call" to "Simu ya Video",
            "voice_call" to "Simu ya Sauti",
            "end_call" to "Maliza",
            "mute" to "Nyamazisha",
            "speaker" to "Spika",
            "camera" to "Kamera",
            "save" to "Hifadhi",
            "cancel" to "Ghairi",
            "delete" to "Futa",
            "edit" to "Hariri",
            "share" to "Shirikisha",
            "rate" to "Pima",
            "review" to "Toa Maoni",
            "report" to "Ripoti",
            "help" to "Msaada",
            "settings" to "Mipangilio",
            "logout" to "Toka",
            "loading" to "Inapakia...",
            "error" to "Kuna shida imetokea",
            "retry" to "Jaribu Tena",
            "no_results" to "Hakuna matokeo",
            "empty_chats" to "Hakuna ujumbe bado",
            "empty_orders" to "Hakuna maagizo bado",
            "crops" to "Mazao",
            "livestock" to "Mifugo",
            "products" to "Bidhaa",
            "services" to "Huduma",
            "price" to "Bei",
            "quantity" to "Kiasi",
            "quality" to "Ubora",
            "location" to "Mahali",
            "description" to "Maelezo",
            "organic" to "Kiasili",
            "grade" to "Kiwango",
            "farmer" to "Mkulima",
            "buyer" to "Mnunuzi",
            "rider" to "Dereva",
            "verified" to "Imethibitishwa",
            "rating" to "Ukadiriaji",
            "sales" to "Mauzo",
            "orders" to "Maagizo",
            "earnings" to "Mapato",
            "savings" to "Akiba",
            "loan" to "Mkopo",
            "insure" to "Bima"
        )
    )
    
    fun getString(context: Context, key: String): String {
        val lang = LanguageManager.getCurrentLanguage(context)
        return translations[lang]?.get(key) 
            ?: translations["en"]?.get(key) 
            ?: key
    }
}
